#include <stdio.h>

//ROS2 rclc stuff
#include <rclc/rclc.h>

#include <geometry_msgs/msg/point.h>
//#include <unistd.h>

#include <rcutils/get_env.h>

//Lua5.2
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>


const lua_State* init_lua() {
   lua_State* L = luaL_newstate();
   luaL_openlibs(L);
   return L;
}

void destroy_lua(lua_State* L) {
  lua_close(L);
}

int execute_file(lua_State* L, const char* name) {
    int error = luaL_loadfile(L,name);
    if (error != 0) {
        fprintf(stderr, "executeFile : error during loading/compiling :\n  %s\n ",lua_tostring(L, -1)); 
        lua_pop(L, 1);  /* pop error message from the stack */
        return 1;
    }
    error = lua_pcall(L,0,0,0);
    if (error != 0) {
      fprintf(stderr,"executeFile : error during execution :\n  %s\n ",lua_tostring(L, -1)); 
        lua_pop(L, 1);  /* pop error message from the stack */
        return 2;
    }
    return 0;
}

//singleton
lua_State* L;

//should be autogenerated
int push_geometry_msgs__msg__Point(geometry_msgs__msg__Point* msg) {
  lua_getglobal(L,"ffi");
  lua_getfield(L,1,"new");
  lua_pushstring(L,"geometry_msgs__msg__Point*"); //TODO concatenate name type with pointer symbol
  lua_pushlightuserdata(L,(void*)(msg));
  lua_call(L,2,1);
  lua_setglobal(L,"msg");
//   printf("size: %d\n",lua_gettop(L));
  lua_pop(L,1);
  return 0;
}

void callback(const void* msg) {
  geometry_msgs__msg__Point* data = (geometry_msgs__msg__Point*)(msg);
//   printf("Received! %f %f %f\n", data->x, data->y, data->z);
  push_geometry_msgs__msg__Point(msg);
  execute_file(L,"/home/haianos/ros2_ws/src/dconv_rclc_example/dconv_rclc_example/script/loop.lua");
}


int main(int argc, char** argv) {
  printf("Starting up...\n");
  rclc_init(0, NULL);
  rclc_node_t* node = rclc_create_node("subnode", "/ns");
  L = init_lua();
  
  const char* env_value;
  const char* error_str;
  error_str = rcutils_get_env("DCONV", &env_value);
  if (error_str != NULL) {
   fprintf(stderr, "Error getting env var: %s\n", error_str);
  }
  printf("Valued of 'DCONV': %s\n", env_value);
  
  char initscript[256];
  strcat(initscript,env_value);
  strcat(initscript,"/testing.lua\0");
  printf("initscript %s\n", initscript);
  
  execute_file(L,"/home/haianos/ros2_ws/src/dconv_rclc_example/dconv_rclc_example/script/testing.lua");
//   execute_file(L,initscript);
  
  rclc_subscription_t * sub =
      rclc_create_subscription(node,
        RCLC_GET_MSG_TYPE_SUPPORT(geometry_msgs, msg, Point),
        "topic", callback, 0, false);
    

  rclc_spin_node(node);
  
  printf("Bye!!\n");
  rclc_destroy_subscription(sub);
  destroy_lua(L);
  rclc_destroy_node(node);
  return 0;
}